### ISSUE TITLE
Better debug logging when unable to map type

### ISSUE THREAD

**Issue by PerfectlyNormal** [PerfectlyNormal/TypeContractor#20]
Write which type fails to be generated and what caused it to be included

**Comment by PerfectlyNormal** [comment]
```
  [INFO] Writing types.
  Unhandled exception: System.ArgumentException: Unable to find type for System.Collections.Generic.Dictionary`2[System.DateTimeOffset,System.Collections.Generic.IEnumerable`1[MyDto]]
     at TypeContractor.TypeScript.TypeScriptWriter.BuildImports(OutputType type, IEnumerable`1 allTypes) in /home/runner/work/TypeContractor/TypeContractor/TypeContractor/TypeScript/TypeScriptWriter.cs:line 60
     at TypeContractor.TypeScript.TypeScriptWriter.Write(OutputType outputType, IEnumerable`1 allTypes) in /home/runner/work/TypeContractor/TypeContractor/TypeContractor/TypeScript/TypeScriptWriter.cs:line 25
     at TypeContractor.Contractor.Build(MetadataLoadContext metadataLoadContext, Boolean smartClean) in /home/runner/work/TypeContractor/TypeContractor/TypeContractor/Contractor.cs:line 86
     at TypeContractor.Tool.Generator.Execute() in /home/runner/work/TypeContractor/TypeContractor/TypeContractor.Tool/Generator.cs:line 104
     at Program.<>c__DisplayClass0_0.<<<Main>$>b__3>d.MoveNext() in /home/runner/work/TypeContractor/TypeContractor/TypeContractor.Tool/Program.cs:line 31
  --- End of stack trace from previous location ---
     at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
     at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
```

**Comment by PerfectlyNormal** [comment]
Fixed
