### ISSUE TITLE
Can attempt to load an assembly twice

### ISSUE THREAD

**Issue by PerfectlyNormal** [PerfectlyNormal/TypeContractor#28]
```csharp
Unhandled exception: System.IO.FileLoadException: The assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' has already loaded been loa
  ded into this MetadataLoadContext.
     at System.Reflection.MetadataLoadContext.LoadFromStreamCore(Stream peStream)
     at System.Reflection.MetadataLoadContext.LoadFromAssemblyPath(String assemblyPath)
     at System.Reflection.PathAssemblyResolver.Resolve(MetadataLoadContext context, AssemblyName assemblyName)
     at System.Reflection.MetadataLoadContext.TryFindAssemblyByCallingResolveHandler(RoAssemblyName refName)
     at System.Reflection.MetadataLoadContext.ResolveToAssemblyOrExceptionAssembly(RoAssemblyName refName)
     at System.Reflection.TypeLoading.Ecma.EcmaResolver.<>c.<.cctor>b__15_3(EntityHandle h, EcmaModule m)
     at System.Reflection.TypeLoading.Ecma.MetadataTable`2.GetOrAdd(EntityHandle handle, C context, Func`3 factory)
     at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveToAssemblyOrExceptionAssembly(AssemblyReferenceHandle handle, EcmaModule module)
     at System.Reflection.TypeLoading.Ecma.EcmaResolver.TryResolveAssembly(AssemblyReferenceHandle handle, EcmaModule module, Exception& e)
     at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveAssembly(AssemblyReferenceHandle handle, EcmaModule module)
     at System.Reflection.TypeLoading.Ecma.EcmaResolver.ComputeTypeRefResolution(TypeReferenceHandle handle, EcmaModule module)
     at System.Reflection.TypeLoading.Ecma.EcmaResolver.<>c.<.cctor>b__15_1(EntityHandle h, EcmaModule m)
     at System.Reflection.TypeLoading.Ecma.MetadataTable`2.GetOrAdd(EntityHandle handle, C context, Func`3 factory)
     at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveTypeRef(TypeReferenceHandle handle, EcmaModule module)
     at System.Reflection.TypeLoading.Ecma.EcmaModule.GetTypeFromReference(MetadataReader reader, TypeReferenceHandle handle, Byte rawTypeKind)
     at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeTypeHandle(BlobReader& blobReader, Byte rawTypeKind, Boolean allowTypeSpecifications)
     at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeType(BlobReader& blobReader, Boolean allowTypeSpecifications, Int32 typeCode)
     at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeType(BlobReader& blobReader, Boolean allowTypeSpecifications)
     at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeGenericTypeInstance(BlobReader& blobReader)
     at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeType(BlobReader& blobReader, Boolean allowTypeSpecifications, Int32 typeCode)
     at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeType(BlobReader& blobReader, Boolean allowTypeSpecifications)
     at System.Reflection.Metadata.TypeSpecification.DecodeSignature[TType,TGenericContext](ISignatureTypeProvider`2 provider, TGenericContext genericContext)
     at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveTypeSpec(TypeSpecificationHandle handle, EcmaModule module, TypeContext& typeContext)
     at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveTypeDefRefOrSpec(EntityHandle handle, EcmaModule module, TypeContext& typeContext)
     at System.Reflection.TypeLoading.Ecma.EcmaDefinitionType.SpecializeBaseType(RoType[] instantiation)
     at System.Reflection.TypeLoading.RoDefinitionType.ComputeBaseTypeWithoutDesktopQuirk()
     at System.Reflection.TypeLoading.RoType.ComputeBaseType()
     at System.Reflection.TypeLoading.RoType.GetRoBaseType()
     at System.Reflection.TypeLoading.RoType.get_BaseType()
     at TypeContractor.Helpers.TypeChecks.IsController(Type type) in /home/runner/work/TypeContractor/TypeContractor/TypeContractor/Helpers/TypeChecks.cs:line 87
     at System.Linq.Enumerable.WhereArrayIterator`1.ToList()
     at TypeContractor.Tool.Generator.Execute() in /home/runner/work/TypeContractor/TypeContractor/TypeContractor.Tool/Generator.cs:line 48
     at Program.<>c__DisplayClass0_0.<<<Main>$>b__4>d.MoveNext() in /home/runner/work/TypeContractor/TypeContractor/TypeContractor.Tool/Program.cs:line 42
  --- End of stack trace from previous location ---
     at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
     at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by PerfectlyNormal** [comment]
Happens when a class we're looking at to in `IsController` inherits from `System.Text.Json.Serialization.JsonConverter<CultureInfo>` and we've already loaded `System.Text.Json` from something else.
